provider:
  name: azureipam
  schema:
    markdown_description: Provider to interact with the Azure IPAM API.
    description: Provider to interact with the Azure IPAM API.  
data_sources:
  admins:
    read:
      path: /api/admin/admins
      method: GET
resources:
  reservation:
    read: 
      path: /api/spaces/{space}/blocks/{block}/reservations/{reservation}
      method: GET
    create:
      path: /api/spaces/{space}/blocks/{block}/reservations
      method: POST
    delete:
      path: /api/spaces/{space}/blocks/{block}/reservations/{reservation}
      method: DELETE
    update:
      path: /api/spaces/{space}/blocks/{block}/reservations
      method: POST  
